CREATE SEQUENCE SEQ_VEICULOS
    START WITH 1
    INCREMENT BY 1 NOCACHE
    NOCYCLE;

CREATE TABLE VEICULO
(
    ID_VEICULO        INTEGER DEFAULT SEQ_VEICULOS.NEXTVAL NOT NULL,
    MODELO_VEICULO    VARCHAR        (100)            NOT NULL
);

CREATE SEQUENCE SEQ_CAMERAS
    START WITH 1
    INCREMENT BY 1 NOCACHE
    NOCYCLE;

CREATE TABLE CAMERA
(
    ID_CAMERA               INTEGER DEFAULT SEQ_CAMERAS.NEXTVAL NOT NULL,

    QT_PASSAGEM_VEICULO     INTEGER                         NOT NULL,
    DATA_PASSAGEM_VEICULO   DATE                            NOT NULL,
    NM_AVENIDA              VARCHAR2        (100)            NOT NULL
);
