CREATE SEQUENCE SEQ_CENTRAL
    START WITH 1
    INCREMENT BY 1 NOCACHE
    NOCYCLE;

CREATE TABLE CENTRAL
(
    ID_CENTRAL          INTEGER DEFAULT SEQ_CENTRAL.NEXTVAL NOT NULL,
    USER_NAME_CENTRAL   VARCHAR2(100)                       NOT NULL,
    SENHA_ACESSO        VARCHAR2(100)                       NOT NULL,
    "ROLE"              VARCHAR2(100)   DEFAULT USER        NOT NULL,
    CONSTRAINT          CENTRAL_PK      PRIMARY KEY         (ID_CENTRAL),
    CONSTRAINT          CENTRAL_UNIQUE  UNIQUE              (USER_NAME_CENTRAL)

)









